version: "1.0"
fail_fast: false
indicators:
  - slack_notify: &slack_notify
      stage: notifications
      type: slack-message-sender
      arguments:
        WEBHOOK_URL: '${{SLACK_DEVOPS_HOOK_URL}}'
stages:
  - 'notifications'
  - 'clone'
  - 'build'
  - 'push'
  - 'test'
  - 'deploy-staging'
  - 'integration-test'
  - 'deploy-production'
steps:
  NotifyInit:
   <<: *slack_notify
   arguments:
     MESSAGE: 'Initiating ${{CF_REPO_NAME}} Pipeline'
  main_clone:
    type: 'git-clone'
    description: 'Cloning main repository...'
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: 'clone'
  build:
    title: 'Building Docker Image'
    type: 'build'
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: 'Dockerfile'
    stage: 'build'
    scale:
      voteImage:
        working_directory: 'vote'
        title: 'Building vote Image'
        image_name: 'example-voting-app/vote'
      testImage:
        working_directory: 'tests'
        title: 'Building test Image'
        image_name: 'example-voting-app/test'
      resultImage:
        working_directory: 'result'
        image_name: 'example-voting-app/result'
        title: 'Building result Image'
      workerImage:
        working_directory: 'worker'
        image_name: 'example-voting-app/worker'
        title: 'Building worker Image'
  approval_for_push:
    type: 'pending-approval'
    title: 'Should we run push'
    stage: 'push'
    when:
      branch:
        only:
          - 'master'
  push:
    stage: 'push'
    title: 'Pushing image to cfcr'
    type: 'push'
    registry: 'cfcr'
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}"
    scale:
      pushVote:
        title: 'Pushing vote image to cfcr'
        candidate: '${{voteImage}}'
      pushResult:
        title: 'Pushing result image to cfcr'
        candidate: '${{resultImage}}'
      pushWorker:
        title: 'Pushing worker image to cfcr'
        candidate: '${{workerImage}}'
      pushTest:
        title: 'Pushing test image to cfcr'
        candidate: '${{testImage}}'
  lintHelmChart:
    stage: 'test'
    title: Linting Helm Chart
    image: codefresh/cfstep-helm
    commands:
      - bash -c 'cd example-voting-app && helm lint'
  AquaSecurityScan:
    type: aqua
    stage: 'test'
    arguments:
      AQUA_HOST: '${{AQUA_HOST}}'
      AQUA_PASSWORD: '${{AQUA_PASSWORD}}'
      AQUA_USERNAME: '${{AQUA_USERNAME}}'
      IMAGE: '${{IMAGE}}'
      TAG: '${{CF_BRANCH_TAG_NORMALIZED}}'
    scale:
      ScanVote:
        title: 'Scan vote image'
        arguments:
            IMAGE: '${{voteImage}}'
      ScanResult:
        title: 'Scan result image to cfcr'
        arguments:
            IMAGE: '${{resultImage}}'
      ScanWorker:
        title: 'Scan worker image to cfcr'
        arguments:
            IMAGE: '${{workerImage}}'
      ScanTest:
        title: 'Scan test image to cfcr'
        arguments:
            IMAGE: '${{testImage}}'
  PushHelmChart:
    stage: 'push'
    title: push chart for example-voting-app
    image: codefresh/cfstep-helm:2.9.0
    environment:
      - ACTION=push
      - CHART_REF=example-voting-app
  DeployToStaging:
    stage: 'deploy-staging'
    image: 'codefresh/cfstep-helm:2.9.0'
    environment:
      - CHART_REF=example-voting-app
      - RELEASE_NAME=example-staging
      - KUBE_CONTEXT=staging-cluster
      - VALUE_result_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/result
      - VALUE_result_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      - VALUE_vote_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/vote
      - VALUE_vote_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      - VALUE_worker_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/worker
      - VALUE_worker_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    when:
      branch:
        only:
          - 'master'
  RunIntegrationOnStaging:
    stage: 'integration-test'
    title: Running test tools
    image: '${{testImage}}'
    commands:
      - echo "This runs a command inside the test container we created..."
    when:
      branch:
        only:
          - 'master'
  DeployToProduction:
    stage: 'deploy-production'
    image: 'codefresh/cfstep-helm:2.9.0'
    environment:
      - CHART_REF=example-voting-app
      - RELEASE_NAME=example-production
      - KUBE_CONTEXT=production-cluster
      - VALUE_result_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/result
      - VALUE_result_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      - VALUE_vote_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/vote
      - VALUE_vote_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
      - VALUE_worker_image_repository=r.cfcr.io/${{CF_ACCOUNT}}/example-voting-app/worker
      - VALUE_worker_image_tag=${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
    when:
      branch:
        only:
          - 'master'
  NotifyComplete:
   <<: *slack_notify
   arguments:
      MESSAGE: 'Finished ${{CF_REPO_NAME}} Pipeline'
