version: "1.0"
stages:
  - "clone"
  - "build"
  - "integration"
  - "push"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    scale:
      vote:
        working_directory: "vote"
        image_name: "DevopSherpas/example-voting-app-vote"
      result:
        working_directory: "result"
        image_name: "DevopSherpas/example-voting-app-result"
      worker:
        working_directory: "worker"
        image_name: "DevopSherpas/example-voting-app-worker"
  approval_for_push:
    type: "pending-approval"
    title: "Should we run push"
    when:
      branch:
        only:
          - "master"
    stage: "push"
  parallel_push:
    type: "parallel"
    steps:
      push:
        title: "Pushing image to cfcr"
        type: "push"
        registry: "cfcr"
        tags:
          - "${{CF_BRANCH_TAG_NORMALIZED}}"
          - "${{CF_REVISION}}"
        scale:
          vote:
            image_name: "DevopSherpas/example-voting-app-vote"
            candidate: "${{vote}}"
          result:
            image_name: "DevopSherpas/example-voting-app-result"
            candidate: "${{result}}"
          worker:
            image_name: "DevopSherpas/example-voting-app-worker"
            candidate: "${{worker}}"
    stage: "push"
