# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: aperturesci.jfrog.io/demo-docker/vote
  tag: pr-20-change-vote-app-b-to-birds-1797dcf
redis:
  usePassword: false
replicaCount: 1
